version: '3'

services:
  postgres:
    image: postgres:11
    container_name: gympoint-postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gympoint
      - POSTGRES_PASSWORD=docker

  redis:
    image: redis:alpine
    container_name: gympoint-redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
